### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iwofjr** [JericoFX/fx-computermdt#1]
**Describe the bug**
Everytime I give someone a fine it adds on to the previous fine even though I paid the previous fine.

**To Reproduce**
Give yourself fines

**Expected behavior**
Have a new fine and not the fine cost to stack up on each other

**Screenshots**

**Additional context**

**Comment by JericoFX** [comment]
Do you have a video of it? because i dont understand, so, if you give yourself some fines, and if you try to pay the last one, the first one disappeared? is that the bug?

**Comment by iwofjr** [comment]
> Do you have a video of it? because i dont understand, so, if you give yourself some fines, and if you try to pay the last one, the first one disappeared? is that the bug?

**Comment by iwofjr** [comment]
> Do you have a video of it? because i dont understand, so, if you give yourself some fines, and if you try to pay the last one, the first one disappeared? is that the bug?

No whats happening is once I pay a fine and I get another fine it just keeps adding from the previous fine. Say I got a 3000 dollar fine and I pay it clears i payed the 3000$ fine but then if I get a new fine it adds onto the previous so If my next fine is a 600$ fine the fine when I go pay it is 3600$

**Comment by iwofjr** [comment]
> > Do you have a video of it? because i dont understand, so, if you give yourself some fines, and if you try to pay the last one, the first one disappeared? is that the bug?
> 
> No whats happening is once I pay a fine and I get another fine it just keeps adding from the previous fine. Say I got a 3000 dollar fine and I pay it clears i payed the 3000$ fine but then if I get a new fine it adds onto the previous so If my next fine is a 600$ fine the fine when I go pay it is 3600$

hopefully this make sense.

**Comment by JericoFX** [comment]
ooohh i see, thanks for the report, im on it right now

**Comment by iwofjr** [comment]
> ooohh i see, thanks for the report, im on it right now

Perfect

**Comment by JericoFX** [comment]
can you try the new update?

**Comment by iwofjr** [comment]
> can you try the new update?

yep it fixed it
