### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iwofjr** [JericoFX/fx-computermdt#2]
**Describe the bug**
After using the MDT once and making a report, It doesn't let you into the MDT its just an invisible screen.

**To Reproduce**
Steps to reproduce the behavior: Give yourself a report go pay the fine go back into your car do /mdt and the MDT screen goes invisble

**Expected behavior**
For the MDT to reappear.

**Screenshots**
(https://prnt.sc/iWdVHAT522qu)

**Additional context**

**Comment by JericoFX** [comment]
can you try it now?

**Comment by iwofjr** [comment]
> can you try it now?

fixed thanks
